"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 20:53:05.821013
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_household")),
    )
    op.create_table(
        "product",
        sa.Column("ah_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("unit_size_text", sa.String(length=50), nullable=True),
        sa.Column("unit_amount", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=2), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("sub_category", sa.String(length=100), nullable=True),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("min_best_before_days", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ah_id", name=op.f("pk_product")),
    )
    op.create_table(
        "worker_heartbeat",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("beat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_worker_heartbeat")),
    )
    op.create_table(
        "action_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("undo_payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_action_log_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_log")),
    )
    op.create_table(
        "ah_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("tokens_enc", sa.LargeBinary(), nullable=False),
        sa.Column("is_order_account", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_ah_account_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ah_account")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("pw_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_app_user_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "bonus_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week", sa.String(length=10), nullable=False),
        sa.Column("ah_product_id", sa.Integer(), nullable=False),
        sa.Column("mechanism", sa.String(length=100), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ah_product_id"], ["product.ah_id"], name=op.f("fk_bonus_offer_ah_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bonus_offer")),
        sa.UniqueConstraint("week", "ah_product_id", name=op.f("uq_bonus_offer_week")),
    )
    op.create_table(
        "pause",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_pause_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pause")),
    )
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("ah_order_id", sa.Integer(), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("cutoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_plan_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
    )
    op.create_table(
        "price_observation",
        sa.Column("ah_product_id", sa.Integer(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("regular_price", sa.Float(), nullable=True),
        sa.Column("is_bonus", sa.Boolean(), nullable=False),
        sa.Column("bonus_mechanism", sa.String(length=100), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ah_product_id"],
            ["product.ah_id"],
            name=op.f("fk_price_observation_ah_product_id_product"),
        ),
        sa.PrimaryKeyConstraint("ah_product_id", "observed_on", name=op.f("pk_price_observation")),
    )
    op.create_table(
        "product_family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_unit", sa.String(length=2), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("carryover", sa.Float(), nullable=False),
        sa.Column("correction", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_product_family_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_family")),
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("ah_order_id", sa.Integer(), nullable=False),
        sa.Column("ah_product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("delivered_at", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["ah_product_id"], ["product.ah_id"], name=op.f("fk_purchase_ah_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_purchase_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase")),
        sa.UniqueConstraint(
            "household_id", "ah_order_id", "ah_product_id", name=op.f("uq_purchase_household_id")
        ),
    )
    with op.batch_alter_table("purchase", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_delivered_at"), ["delivered_at"], unique=False
        )

    op.create_table(
        "family_member",
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("ah_product_id", sa.Integer(), nullable=False),
        sa.Column("preferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ah_product_id"],
            ["product.ah_id"],
            name=op.f("fk_family_member_ah_product_id_product"),
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["product_family.id"],
            name=op.f("fk_family_member_family_id_product_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("family_id", "ah_product_id", name=op.f("pk_family_member")),
    )
    op.create_table(
        "family_stats",
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("rate_per_day", sa.Float(), nullable=True),
        sa.Column("cv_interval", sa.Float(), nullable=True),
        sa.Column("n_purchases", sa.Integer(), nullable=False),
        sa.Column("last_purchase_at", sa.Date(), nullable=True),
        sa.Column("est_stock", sa.Float(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("bonus_interval_days", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["product_family.id"],
            name=op.f("fk_family_stats_family_id_product_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("family_id", name=op.f("pk_family_stats")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["product_family.id"],
            name=op.f("fk_feedback_family_id_product_family"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_feedback_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_table(
        "plan_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("ah_product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=30), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=12), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ah_product_id"], ["product.ah_id"], name=op.f("fk_plan_line_ah_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["product_family.id"],
            name=op.f("fk_plan_line_family_id_product_family"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plan.id"], name=op.f("fk_plan_line_plan_id_plan"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_line")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_line")
    op.drop_table("feedback")
    op.drop_table("family_stats")
    op.drop_table("family_member")
    with op.batch_alter_table("purchase", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_delivered_at"))

    op.drop_table("purchase")
    op.drop_table("product_family")
    op.drop_table("price_observation")
    op.drop_table("plan")
    op.drop_table("pause")
    op.drop_table("bonus_offer")
    op.drop_table("app_user")
    op.drop_table("ah_account")
    op.drop_table("action_log")
    op.drop_table("worker_heartbeat")
    op.drop_table("product")
    op.drop_table("household")
    # ### end Alembic commands ###
