"""store receipts

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 19:45:29.489876
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_product_map",
        sa.Column("pos_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("ah_product_id", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pos_id", name=op.f("pk_pos_product_map")),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hq_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_product_hq_id"), ["hq_id"], unique=False)

    with op.batch_alter_table("purchase", schema=None) as batch_op:
        batch_op.add_column(sa.Column("receipt_id", sa.String(length=64), nullable=True))
        batch_op.alter_column("ah_order_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_unique_constraint(
            "uq_purchase_receipt_line", ["household_id", "receipt_id", "ah_product_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Store-receipt lines have no order id and cannot exist in the old schema; they can be
    # imported again after upgrading.
    op.execute("DELETE FROM purchase WHERE receipt_id IS NOT NULL OR ah_order_id IS NULL")
    with op.batch_alter_table("purchase", schema=None) as batch_op:
        batch_op.drop_constraint("uq_purchase_receipt_line", type_="unique")
        batch_op.alter_column("ah_order_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("receipt_id")

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_hq_id"))
        batch_op.drop_column("hq_id")

    op.drop_table("pos_product_map")
    # ### end Alembic commands ###
