from datetime import date
from typing import Protocol

from app.ah.models import (
    ActiveOrderSummary,
    BonusMetadata,
    Fulfillment,
    LineItem,
    OrderDetails,
    Product,
    Tokens,
    UpcomingOrder,
)


class AhClient(Protocol):
    """The single interface to AH (SPEC §4). Implementations: HttpAhClient, fakes in tests."""

    async def login_url(self) -> str: ...
    async def exchange_code(self, code: str) -> Tokens: ...
    async def refresh(self, tokens: Tokens) -> Tokens: ...

    async def list_orders(self, since: date) -> list[Fulfillment]: ...
    async def get_order(self, order_id: int) -> OrderDetails: ...

    async def get_product(self, product_id: int) -> Product: ...
    async def search_products(self, query: str) -> list[Product]: ...
    async def get_bonus_metadata(self) -> BonusMetadata: ...

    async def get_upcoming_order(self) -> UpcomingOrder | None: ...
    async def reopen_order(self, order_id: int) -> None: ...
    async def revert_order(self, order_id: int) -> None: ...
    async def add_to_order(
        self, order_id: int, items: list[LineItem]
    ) -> ActiveOrderSummary | None: ...
